# Generated by Django 2.0.2 on 2018-03-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('inv_number', models.CharField(max_length=100, verbose_name='Инвентарный номер')),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_unit', models.DecimalField(decimal_places=0, max_digits=18)),
                ('id_equipment', models.DecimalField(decimal_places=0, max_digits=18)),
            ],
            options={
                'db_table': 'Junction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.CharField(max_length=500, verbose_name='Описание работ')),
                ('time', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Время выполнения (мин.)')),
                ('periodicity', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Периодичность (дн.)')),
                ('photo', models.FileField(blank=True, max_length=50, null=True, upload_to='media/', verbose_name='Изображение')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Untigroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'untiGroup',
                'managed': False,
            },
        ),
    ]
