# Generated by Django 2.0.2 on 2018-03-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='inv_number',
            field=models.CharField(default='111', max_length=200, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='model',
            field=models.CharField(max_length=200, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
    ]
