# Generated by Django 2.0.2 on 2018-03-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20180305_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='equipment_id',
            new_name='equipment',
        ),
    ]
