# Generated by Django 2.0.2 on 2018-03-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20180305_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='equipment',
        ),
    ]
