# Generated by Django 2.0.2 on 2018-03-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20180316_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentEquipUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.IntegerField()),
            ],
            options={
                'db_table': 'equipment_equip_units',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='equip',
            name='equipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='units',
            field=models.ManyToManyField(through='equipment.EquipmentEquipUnits', to='equipment.Unit'),
        ),
    ]
