# Generated by Django 2.0.2 on 2018-03-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_remove_unit_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
