# Generated by Django 2.0.2 on 2018-03-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20180319_0936'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maintenance',
            table='maintenance',
        ),
    ]
