# Generated by Django 2.0.2 on 2018-03-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_auto_20180305_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='equipment',
            field=models.ManyToManyField(to='equipment.Unit', verbose_name='Выбрать узлы'),
        ),
    ]
