# Generated by Django 2.0.2 on 2018-03-07 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_equipmenttype_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.Unit'),
        ),
    ]
