# Generated by Django 2.0.2 on 2018-03-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_auto_20180307_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='equipment',
            field=models.ManyToManyField(to='equipment.Unit', verbose_name='Выбрать узлы'),
        ),
    ]
