# Generated by Django 2.0.2 on 2018-03-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_auto_20180307_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmenttype',
            old_name='equipment',
            new_name='units',
        ),
    ]
